### ISSUE TITLE
Integrating external files into milestone.xml and the modified files package

### ISSUE THREAD

**Issue by ckab74** [oxygenxml/oxygen-dita-translation-package-builder#18]
We use many shared external topics that contain, for example, only parameters (plentry elements). The topics are not connected to any ditamaps, but the parameters are referenced (conrefed) from files that are connected to the main ditamap. The reason we do this is that we use the parameters in various orders in multiple topics, so we cannot create one topic with all parameters and reference those from the other topics. 
These external topics are usually also exported if we use the Export DITA Map function in oXygen. When creating a milestone or a modified files package, these shared external topics are unfortunately ignored.

**Comment by raducoravu** [comment]
Strange, this should work. Could you put together a small sample DITA project to demonstrate this? Are those external topics outside of the folder where the main DITA Map is located?

**Comment by ckab74** [comment]
The external topics are actually in the same folder as the "normal" topics. I think the issue relates to the fact that the files in which the parameters are "conrefed" actually contain no text, but links. Other external topics that contain text, but are way outside of the folder of the main ditamap, are taken into account if I create the modified files package. Sending you a sample directly.

**Comment by raducoravu** [comment]
Thanks @ckab74, we can reproduce this on your side. 
Indeed for topics which are not directly referenced in the DITA Map but have content referenced from other topics using conref the generated milestone ZIP will not contained the topics, even if they were changed. We'll work to fix this and come up with an update for the plugin in 1-2 weeks. You can enable automatic add-ons checking in the Oxygen **Preferences**->**Add-ons** page in order to be notified.

**Comment by raducoravu** [comment]
The code should not use the file extension of the referenced files for anything. A DITA topic is referenced using format="dita" or the empty format and no matter what its extension is, it is still a DITA topic. 
So the set of visited URLs should also contain information about the @format attribute which was used to refer to them, in this way we know if the URL is a DITA resource or a non-DITA resource.
