### ISSUE TITLE
Issues when creating modified files package

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-dita-translation-package-builder#6]
I press the action, the dialog shows. If when showing the dialog we already know the modified files I would kind of like a label in the dialog saying something like:

"A number of X files was modified since the last time the milestone was computed. More details..."
And pressing the "More details" could maybe show the list of files which will be packed in the zip... maybe...

**Comment by AdrianSorop** [comment]
I think is done.
