### ISSUE TITLE
The root map might not be in the top folder

### ISSUE THREAD

**Issue by AlexJitianu** [oxygenxml/oxygen-dita-translation-package-builder#9]
Currently, when building the milestone file, as well as the package, we assume that the map is in the top folder. Sometimes, the structure of the project is something like this:

-root
--topics
----a.dita
--images
----a.png
--maps
----***my_map.ditamap***

The milestone file
=====================
If we analyze the map structure (see #8 ) then we will know all the resources and we can infer the root folder. We can:
1. put the milestone file next to the map as we do now
2. since multiple maps can reside in the same folder we can name the file milestone-**myMapName**.xml
3. keep in the milestone file the information about where the root folder is (as a relative path):
`<resources rootFolder="../../">`

The package
=====================
We probably have to put the milestone file inside the package. This way, when it returns and the user applies it over the map, we can extract the root folder from it:
``<resources rootFolder="../../">``

**Comment by raducoravu** [comment]
👍 We had another user who wants to start the creation of the milestone document starting from a DITA Map:

> We would like to be able to export new/changed files that are specific to a selected root map

so they probably also need to decide the location where the milestone document will be saved.

**Comment by DalinaBivolan** [comment]
[Translation_Package_Builder.zip](https://github.com/oxygenxml/Translation-Package-Builder/files/1343886/Translation_Package_Builder.zip)

This is the patch file with the current state of the plugin.

**Comment by dliu-st** [comment]
Hi Dalina/Radu,
I downloaded this patch file, but I don't know what to do next.
Thanks!
Di

**Comment by raducoravu** [comment]
@dliu-st The patch is something we need internally, the issue is not yet closed.  If in the Oxygen Preferences->"Add-ons" you check the "Enable automatic add-ons checking" Oxygen will notify you when a new version of the plugin is available.

**Comment by dliu-st** [comment]
OK, now I understand. Thank you!
Di

**Comment by fviolette** [comment]
Hello,

Thanks for the plugin. We have met this issue in our project too - is this fixed if I install the plugin at HEAD revision?

**Comment by AlexJitianu** [comment]
Hello,

Thank you for your interest into this plugin. Unfortunately, this feature is not yet completed. I will increase its priority and, hopefully, it wont take long until it's finish.

**Comment by dliu-st** [comment]
OK, thank you!
Di

**Comment by fviolette** [comment]
Release 1.0.11 seems to work better for this.
Apart from missing translations, is there any critical limitation to creating milestones with such folder structures now?

**Comment by AlexJitianu** [comment]
Hi,

I'm not sure what you mean by the "missing translations" but the new version of the plugin should:
1. identify all changed topics and

**Comment by fviolette** [comment]
Checked for the remaining "TODOs" in the source code and found sole i18n that is all :)
Feature works :+1:

**Comment by AlexJitianu** [comment]
I'm glad to hear it! We will tackle the remaining TODOs on a different issue.
